import { Metadata } from 'next';
import React from 'react'
import '@/app/globals.css'
import AnimatedCursor from 'react-animated-cursor';
export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by Ammar",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en' suppressHydrationWarning >
      <body>
        {children}
        <AnimatedCursor
          innerSize={12}
          outerSize={12}
          color='81, 71, 229'
          outerAlpha={0.2}
          innerScale={0.7}
          outerScale={5}
          clickables={[
            'a',
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            'label[for]',
            'select',
            'textarea',
            'button',
            '.link'
          ]}
        />
      </body>
    </html>
  )
}

export default layout