import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/Header";
import { Poppins } from 'next/font/google';
import AnimatedCursor from "react-animated-cursor"
import Footer from "@/components/Footer";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500'],
  display: 'swap',
  style: 'normal',
});

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by Ammar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${poppins.className} antialiased scroll-smooth overflow-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
        <AnimatedCursor
          innerSize={12}
          outerSize={12}
          color='81, 71, 229'
          outerAlpha={0.2}
          innerScale={0.7}
          outerScale={5}
          clickables={[
            'a',
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            'label[for]',
            'select',
            'textarea',
            'button',
            '.link'
          ]}
        />
      </body>
    </html>
  );
}
