import type { Metadata } from "next";
import type React from "react"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header";
import { Poppins } from 'next/font/google';
import AnimatedCursor from "react-animated-cursor"
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import { SidebarProvider } from "@/components/ui/sidebar";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500'],
  display: 'swap',
  style: 'normal',
});

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by Ammar",
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider>
            <DashboardSidebar />
            <main className="flex-1 overflow-auto">{children}</main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );

}